export const FIRBASE_API_KEY = "/FCODE/TODO_APP/REACT_APP_FIREBASE_API_KEY"
export const FIRBASE_AUTH_DOMAIN = "/FCODE/TODO_APP/REACT_APP_FIREBASE_AUTH_DOMAIN"
export const FIRBASE_PROJECT_ID = "/FCODE/TODO_APP/REACT_APP_FIREBASE_PROJECT_ID"
export const FIRBASE_STORAGE_BUCKET = "/FCODE/TODO_APP/REACT_APP_FIREBASE_STORAGE_BUCKET"
export const FIRBASE_SENDER_ID = "/FCODE/TODO_APP/REACT_APP_FIREBASE_MESSAGING_SENDER_ID"
export const FIRBASE_APP_ID = "/FCODE/TODO_APP/REACT_APP_FIREBASE_APP_ID"
export const AWS_REGION = 'us-east-1'